version: 2

project_name: intervals

builds:
  - id: intervals
    main: ./cmd/intervals
    binary: intervals
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/jonaswide/intervals-cli/internal/version.Version={{.Version}}

archives:
  - id: release
    ids:
      - intervals
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
